<?php

namespace Bindeveloperz\Core\Helper;


class ConstHelper
{

    public static function getCitiesList()
    {
        return explode(',', "Abbottabad,Adezai,Ahmadpur East,Ahmed Nager Chatha,Alipur,Alpuri,Arifwala,Attock,Ayubia,Badin,Bahawalnagar,Bahawalpur,Banda Daud Shah,Bannu,Batkhela,Battagram,Bhakkar,Bhalwal,Birote,Burewala,Chakdara,Chakwal,Chaman,Charsadda,Chichawatni,Chillianwala,Chiniot,Chitral,Dadu,Daggar,Dargai,DaryaKhan,Darya Khan,Daska,Dera Allah Yar,Dera Ghazi Khan,Dera Ismail Khan,Dera Murad jamali,Dhaular,Digri,Dina,Dinga,Dipalpur,Diplo,Dir,Dokri,Drosh,Faisalabad,Fateh jang,Ghakhar Mandi,Ghotki,Gujar Khan,Gujranwala,Gujrat,Gwadar,Haala,Hafizabad,Hangu,Haripur,Haroonabad,Hasilpur,Haveli Lakha,Hub,Hyderabad,Islamkot,jacobabad,jampur,jamshoro,jauharabad,jhang,jhelum,jungshahi,Kalabagh,Kalat,Kamalia,Kamoke,Kandiaro,Karachi,Karak,Karor Lal Esan,Kashmore,Kasur,Keti Bandar,Khairpur,Khanewal,Khanpur,Kharan,Kharian,Khushab,Khuzdar,Kohat,Kot Adu,Kotri,Lahore,Lakki Marwat,Lalamusa,Larkana,Latamber,Layyah,Lodhran,Loralai,Madyan,Mailsi,Mamoori,Mandi Bahauddin,Mansehra,Mardan,Mastuj,Mastung,Matiari,Mehar,Mian Channu,Mianwali,Mingora,Mirpur Khas,Mithani,Mithi,Moro,Multan,Muridke,Murree,Muzaffargarh,Nangarparkar,Narowal,Naudero,NaushahroFeroze,Naushara,Nawabshah,Nazimabad,Nowshera,Nushki,Okara,Paharpur,Pakpattan,Pasni,Pattoki,Peshawar,Pir Mahal,Qila Didar Singh,Quetta,Rabwah,Rahim Yar Khan,Raiwind,Rajanpur,Ranipur,Ratodero,Rawalpindi,Renala Khurd,Rohri,Sadiqabad,Safdarabad,Sahiwal,Saidu Sharif,Sakrand,Sanghar,Sangla Hill,Sarai Alamgir,Sargodha,Shahbandar,Shahdadkot,Shahdadpur,Shahpur Chakar,Shakargarh,Sheikhupura,Shikarpaur,Sialkot,Sibi,Sohawa,Soianwala,Sukkur,Swabi,Swat,Talagang,Tando Adam Khan,Tando Allahyar,Tangi,Tank,Taxila,Thall,Thatta,Timergara,Toba Tek Singh,Tordher,Turbat,Umerkot,Usta Mohammad,Vehari,Wah Cantonment,Warah,Wazirabad,Zhob");
    }

    public static function getCountriesList()
    {
        return array(
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegowina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, the Democratic Republic of the",
            "Cook Islands",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia (Hrvatska)",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands (Malvinas)",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "France Metropolitan",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard and Mc Donald Islands",
            "Holy See (Vatican City State)",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran (Islamic Republic of)",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, Democratic People's Republic of",
            "Korea, Republic of",
            "Kuwait",
            "Kyrgyzstan",
            "Lao, People's Democratic Republic",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libyan Arab Jamahiriya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Macedonia, The Former Yugoslav Republic of",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova, Republic of",
            "Monaco",
            "Mongolia",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia (Slovak Republic)",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "Spain",
            "Sri Lanka",
            "St. Helena",
            "St. Pierre and Miquelon",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen Islands",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan, Province of China",
            "Tajikistan",
            "Tanzania, United Republic of",
            "Thailand",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "Virgin Islands (British)",
            "Virgin Islands (U.S.)",
            "Wallis and Futuna Islands",
            "Western Sahara",
            "Yemen",
            "Yugoslavia",
            "Zambia",
            "Zimbabwe",
        );
    }// getCountriesList end

    public static  function bloodGroupList()
    {
        return [
            "A+"
        ];
    }

}